from concreteFactory import Factory, Factory2, Factory3

if __name__ == '__main__':
    fabric = Factory()
    a = fabric.create_a()
    b = fabric.create_b()
    a.test_a()
    b.test_b()
    print('-----')
    fabric2 = Factory2()
    a1 = fabric2.create_a()
    b1 = fabric2.create_b()
    a2 = fabric2.create_a1()
    b2 = fabric2.create_b1()
    a1.test_a()
    b1.test_b()
    a2.test_a()
    b2.test_b()
    fabric3 = Factory3()
    a1 = fabric3.create_a()
    b1 = fabric3.create_b()
    a2 = fabric3.create_a1()
    b2 = fabric3.create_b1()
    b5 = fabric3.create_b5()
    a1.test_a()
    b1.test_b()
    a2.test_a()
    b2.test_b()
    b5.test_b()
    a2.seo()
